import type { AccountRecord, CentralKitchen, PipelineFy, PipelineStatusId } from "./types";
import { applyKitchen } from "./geo";

export const KITCHENS: CentralKitchen[] = [
  {
    id: "cpu_ggm",
    name: "Gurgaon CPU",
    city: "Gurugram",
    state: "Haryana",
    address: "Sector 18, Udyog Vihar, Gurugram",
    lat: 28.4802,
    lng: 77.0724,
  },
  {
    id: "cpu_nod",
    name: "Noida CPU",
    city: "Noida",
    state: "Uttar Pradesh",
    address: "Sector 63, Noida",
    lat: 28.6278,
    lng: 77.3734,
  },
  {
    id: "cpu_mum",
    name: "Mumbai BKC CPU",
    city: "Mumbai",
    state: "Maharashtra",
    address: "Bandra Kurla Complex, Mumbai",
    lat: 19.0662,
    lng: 72.8678,
  },
  {
    id: "cpu_pun",
    name: "Pune Hinjewadi CPU",
    city: "Pune",
    state: "Maharashtra",
    address: "Hinjewadi Phase 2, Pune",
    lat: 18.5913,
    lng: 73.738,
  },
  {
    id: "cpu_blr",
    name: "Bengaluru Whitefield CPU",
    city: "Bengaluru",
    state: "Karnataka",
    address: "EPIP Zone, Whitefield, Bengaluru",
    lat: 12.9698,
    lng: 77.7499,
  },
  {
    id: "cpu_hyd",
    name: "Hyderabad HITEC CPU",
    city: "Hyderabad",
    state: "Telangana",
    address: "HITEC City, Madhapur, Hyderabad",
    lat: 17.4484,
    lng: 78.3816,
  },
  {
    id: "cpu_che",
    name: "Chennai OMR CPU",
    city: "Chennai",
    state: "Tamil Nadu",
    address: "OMR, Perungudi, Chennai",
    lat: 12.9712,
    lng: 80.2465,
  },
  {
    id: "cpu_kol",
    name: "Kolkata Salt Lake CPU",
    city: "Kolkata",
    state: "West Bengal",
    address: "Salt Lake Sector V, Kolkata",
    lat: 22.576,
    lng: 88.4338,
  },
  {
    id: "cpu_amd",
    name: "Ahmedabad SG CPU",
    city: "Ahmedabad",
    state: "Gujarat",
    address: "SG Highway, Ahmedabad",
    lat: 23.0406,
    lng: 72.5284,
  },
];

type Seed = {
  n: number;
  acc: string;
  client: string;
  site: string;
  type: AccountRecord["accountType"];
  industry: string;
  city: string;
  state: string;
  address: string;
  lat: number;
  lng: number;
  status: PipelineStatusId;
  fy: PipelineFy;
  p: number;
  close: string;
  owner: string;
  stage: string;
  cr: number;
  pax: number;
  biz: AccountRecord["businessType"];
  map: AccountRecord["mapType"];
  served: number;
  services: string;
  cpu: string;
  last: string;
  lastOn: string;
  next: string;
  nextOn: string;
  notes: string;
};

const SEED: Seed[] = [
  {
    n: 1, acc: "meridian", client: "Meridian Technologies", site: "DLF Cyber City",
    type: "Retention", industry: "IT / ITeS", city: "Gurugram", state: "Haryana",
    address: "Building 8, DLF Cyber City, Gurugram 122002", lat: 28.4949, lng: 77.0888,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Ananya Sharma",
    stage: "Live", cr: 8.4, pax: 3200, biz: "B&I", map: "Mix", served: 3200,
    services: "Full-service cafeteria, executive dining, vending", cpu: "cpu_ggm",
    last: "QBR with facilities head", lastOn: "2026-08-22", next: "Menu cycle review",
    nextOn: "2026-09-18", notes: "Anchor NCR account. Strong NPS. Expansion interest at Noida.",
  },
  {
    n: 2, acc: "meridian", client: "Meridian Technologies", site: "Noida Campus",
    type: "Existing Expansion", industry: "IT / ITeS", city: "Noida", state: "Uttar Pradesh",
    address: "Plot 3, Sector 62, Noida 201309", lat: 28.6271, lng: 77.3648,
    status: "proposal_submitted", fy: "FY27", p: 70, close: "2026-10-15", owner: "Ananya Sharma",
    stage: "Negotiation", cr: 4.1, pax: 1800, biz: "B&I", map: "Map 2", served: 0,
    services: "Multi-outlet F&B, night-shift meals", cpu: "cpu_nod",
    last: "Commercials sent", lastOn: "2026-08-28", next: "Procurement committee",
    nextOn: "2026-09-12", notes: "Expansion of DLF contract. Prefers CPU-served model.",
  },
  {
    n: 3, acc: "helios", client: "Helios Manufacturing", site: "Manesar Plant",
    type: "New Logo", industry: "Automotive", city: "Manesar", state: "Haryana",
    address: "IMT Manesar, Sector 8, Gurugram 122051", lat: 28.3548, lng: 76.9376,
    status: "pipeline_fy27", fy: "FY27", p: 40, close: "2026-12-10", owner: "Vikram Singh",
    stage: "Needs Assessment", cr: 6.8, pax: 4200, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "Industrial canteen, 3-shift meals, tea trolleys", cpu: "cpu_ggm",
    last: "Plant walkthrough", lastOn: "2026-07-14", next: "Labour contractor intro",
    nextOn: "2026-09-20", notes: "High pax, unionised canteen. On-site kitchen preferred.",
  },
  {
    n: 4, acc: "apexcare", client: "Apex Care Hospital", site: "Gurugram Flagship",
    type: "New Logo", industry: "Healthcare Provider", city: "Gurugram", state: "Haryana",
    address: "Sector 51, Gurugram 122018", lat: 28.4372, lng: 77.0674,
    status: "proposal_development", fy: "FY27", p: 55, close: "2026-11-02", owner: "Ananya Sharma",
    stage: "Solution Design", cr: 5.2, pax: 1100, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafeteria, diet kitchen", cpu: "cpu_ggm",
    last: "Dietetics workshop", lastOn: "2026-09-01", next: "NABH compliance pack",
    nextOn: "2026-09-11", notes: "Requires FSSAI + NABH aligned patient meal SOPs.",
  },
  {
    n: 5, acc: "northcrest", client: "Northcrest University", site: "Sohna Campus",
    type: "New Logo", industry: "Higher Education", city: "Sohna", state: "Haryana",
    address: "Sohna Road, Gurugram 122103", lat: 28.2471, lng: 77.0659,
    status: "pipeline_fy26", fy: "FY26", p: 25, close: "2026-09-30", owner: "Vikram Singh",
    stage: "Commercials", cr: 3.6, pax: 2400, biz: "Education", map: "Map 1", served: 0,
    services: "Hostel mess, faculty dining, kiosks", cpu: "cpu_ggm",
    last: "Price revision ask", lastOn: "2026-05-18", next: "Re-engage chancellor office",
    nextOn: "2026-09-16", notes: "FY26 slippage. Quiet since May. Mess committee political.",
  },
  {
    n: 6, acc: "vantage", client: "Vantage Auto Components", site: "Bawal Works",
    type: "New Logo", industry: "Automotive", city: "Bawal", state: "Haryana",
    address: "Bawal Industrial Area, Rewari 123501", lat: 28.1184, lng: 76.5862,
    status: "prospect_research", fy: "FY27", p: 15, close: "2027-02-28", owner: "Vikram Singh",
    stage: "Discovery", cr: 2.4, pax: 1600, biz: "Manufacturing", map: "Map 2", served: 0,
    services: "Industrial canteen", cpu: "cpu_ggm",
    last: "Desk research + GST lookup", lastOn: "2026-08-04", next: "Cold outreach to GM Admin",
    nextOn: "2026-09-09", notes: "Far from Gurgaon CPU — road time is the feasibility question.",
  },
  {
    n: 7, acc: "lumen", client: "Lumen Bank", site: "Connaught Place HQ",
    type: "Retention", industry: "BFSI", city: "New Delhi", state: "Delhi",
    address: "Barakhamba Road, Connaught Place, New Delhi 110001", lat: 28.6304, lng: 77.2245,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Ananya Sharma",
    stage: "Live", cr: 2.8, pax: 650, biz: "B&I", map: "Map 2", served: 650,
    services: "Executive dining, pantry, cafe", cpu: "cpu_ggm",
    last: "Contract year-3 review", lastOn: "2026-08-12", next: "SLA dashboard",
    nextOn: "2026-09-25", notes: "Prestige site. CPU-served from Gurgaon works well.",
  },
  {
    n: 8, acc: "lumen", client: "Lumen Bank", site: "Gurugram Operations Centre",
    type: "Existing Expansion", industry: "BFSI", city: "Gurugram", state: "Haryana",
    address: "Golf Course Extension Road, Gurugram 122102", lat: 28.4086, lng: 77.0701,
    status: "pipeline_fy28", fy: "FY28", p: 35, close: "2027-06-30", owner: "Ananya Sharma",
    stage: "Discovery", cr: 3.1, pax: 1400, biz: "B&I", map: "Mix", served: 0,
    services: "24x7 cafeteria, pantry network", cpu: "cpu_ggm",
    last: "Facilities intro", lastOn: "2026-09-02", next: "Occupancy forecast",
    nextOn: "2026-10-01", notes: "New ops centre opening FY28. Early relationship seeding.",
  },
  {
    n: 9, acc: "silverline", client: "Silverline IT Park", site: "Noida Tower A-C",
    type: "Strategic", industry: "SEZ / Campus", city: "Noida", state: "Uttar Pradesh",
    address: "Sector 135, Noida 201304", lat: 28.5022, lng: 77.4108,
    status: "proposal_submitted", fy: "FY27", p: 65, close: "2026-09-28", owner: "Ananya Sharma",
    stage: "Submitted", cr: 11.5, pax: 5600, biz: "B&I", map: "Mix", served: 0,
    services: "Campus F&B, food court, dark kitchen", cpu: "cpu_nod",
    last: "Proposal submitted to JLL", lastOn: "2026-08-19", next: "Developer board",
    nextOn: "2026-09-14", notes: "Multi-tenant IT park. Highest-value NCR bid this quarter.",
  },
  {
    n: 10, acc: "cascade", client: "Cascade Pharma", site: "Bhiwadi Formulation",
    type: "New Logo", industry: "Pharma", city: "Bhiwadi", state: "Rajasthan",
    address: "RIICO Industrial Area, Bhiwadi 301019", lat: 28.2089, lng: 76.8604,
    status: "pipeline_fy27", fy: "FY27", p: 30, close: "2027-01-20", owner: "Vikram Singh",
    stage: "Needs Assessment", cr: 3.9, pax: 2100, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "GMP canteen, restricted-diet lines", cpu: "cpu_ggm",
    last: "EHS questionnaire", lastOn: "2026-06-21", next: "Plant HR reconnect",
    nextOn: "2026-09-22", notes: "Stale since June. GMP hygiene bar is high.",
  },
  {
    n: 11, acc: "harbor", client: "Harbor Schools Group", site: "Greater Noida Campus",
    type: "New Logo", industry: "K-12 Education", city: "Greater Noida", state: "Uttar Pradesh",
    address: "Knowledge Park II, Greater Noida 201310", lat: 28.4744, lng: 77.503,
    status: "universe", fy: "FY28", p: 10, close: "2027-08-01", owner: "Ananya Sharma",
    stage: "", cr: 1.6, pax: 1800, biz: "Education", map: "Map 1", served: 0,
    services: "School meals, staff cafe", cpu: "cpu_nod",
    last: "Added from universe scrape", lastOn: "2026-07-02", next: "Map parent trust",
    nextOn: "2026-10-05", notes: "Universe record. Midday meal quality is the entry point.",
  },
  {
    n: 12, acc: "fortwell", client: "Fortwell Hospital", site: "South Delhi",
    type: "New Logo", industry: "Healthcare Provider", city: "New Delhi", state: "Delhi",
    address: "Saket, New Delhi 110017", lat: 28.5284, lng: 77.2192,
    status: "lost", fy: "FY26", p: 0, close: "2026-04-12", owner: "Ananya Sharma",
    stage: "Closed Lost", cr: 4.4, pax: 900, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafeteria", cpu: "cpu_ggm",
    last: "Lost to incumbent on price", lastOn: "2026-04-12", next: "12-month rebid watch",
    nextOn: "2027-01-15", notes: "Lost on price. Close to Lumen CP and Apex Care — cluster play later.",
  },
  {
    n: 13, acc: "keystone", client: "Keystone SEZ", site: "Gurugram Campus",
    type: "Strategic", industry: "SEZ / Campus", city: "Gurugram", state: "Haryana",
    address: "Sector 48, Gurugram 122018", lat: 28.4178, lng: 77.0366,
    status: "won", fy: "FY26", p: 100, close: "2026-03-20", owner: "Ananya Sharma",
    stage: "Closed Won", cr: 9.7, pax: 4100, biz: "B&I", map: "Mix", served: 0,
    services: "Food court, CPU commissary, cafe brands", cpu: "cpu_ggm",
    last: "Mobilisation kickoff", lastOn: "2026-08-30", next: "Go-live 1 Oct",
    nextOn: "2026-10-01", notes: "Won FY26. Mobilising. Nearby prospects can ride this CPU density.",
  },
  {
    n: 14, acc: "riviera", client: "Riviera Foods HQ", site: "Okhla Office",
    type: "New Logo", industry: "FMCG", city: "New Delhi", state: "Delhi",
    address: "Okhla Phase III, New Delhi 110020", lat: 28.5493, lng: 77.2732,
    status: "prospect_research", fy: "FY27", p: 20, close: "2026-12-18", owner: "Ananya Sharma",
    stage: "Discovery", cr: 1.1, pax: 280, biz: "B&I", map: "Map 2", served: 0,
    services: "HQ cafe, pantry", cpu: "cpu_ggm",
    last: "LinkedIn connect with CHRO", lastOn: "2026-08-26", next: "Site visit request",
    nextOn: "2026-09-15", notes: "Small HQ pax but brand-visible FMCG logo.",
  },
  {
    n: 15, acc: "horizon", client: "Horizon Capital", site: "BKC Tower",
    type: "Retention", industry: "BFSI", city: "Mumbai", state: "Maharashtra",
    address: "G Block, Bandra Kurla Complex, Mumbai 400051", lat: 19.0611, lng: 72.8638,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Rohan Mehta",
    stage: "Live", cr: 3.4, pax: 720, biz: "B&I", map: "Map 2", served: 720,
    services: "Executive dining, trading-floor pantry", cpu: "cpu_mum",
    last: "Monsoon menu refresh", lastOn: "2026-08-08", next: "Diwali service plan",
    nextOn: "2026-10-08", notes: "Flagship west-side client. CPU is 800m away.",
  },
  {
    n: 16, acc: "deccan", client: "Deccan Steel", site: "Navi Mumbai Mill",
    type: "New Logo", industry: "Engineering", city: "Navi Mumbai", state: "Maharashtra",
    address: "TTC Industrial Area, Navi Mumbai 400710", lat: 19.1056, lng: 73.0202,
    status: "pipeline_fy26", fy: "FY26", p: 45, close: "2026-09-22", owner: "Rohan Mehta",
    stage: "Commercials", cr: 7.2, pax: 3800, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "Industrial canteen, 3-shift, PPE-zone meals", cpu: "cpu_mum",
    last: "BOQ submitted", lastOn: "2026-08-16", next: "CFO meeting",
    nextOn: "2026-09-08", notes: "Closure this month. High pax, on-site kitchen.",
  },
  {
    n: 17, acc: "sagar", client: "Sagar Hospitals", site: "Andheri West",
    type: "New Logo", industry: "Healthcare Provider", city: "Mumbai", state: "Maharashtra",
    address: "Veera Desai Road, Andheri West, Mumbai 400053", lat: 19.1364, lng: 72.8296,
    status: "proposal_development", fy: "FY27", p: 50, close: "2026-11-18", owner: "Rohan Mehta",
    stage: "Solution Design", cr: 4.8, pax: 980, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafeteria, visitor cafe", cpu: "cpu_mum",
    last: "Kitchen layout draft", lastOn: "2026-09-03", next: "JCI gap assessment",
    nextOn: "2026-09-19", notes: "Wants mix of on-site diet kitchen + CPU bulk.",
  },
  {
    n: 18, acc: "peninsula", client: "Peninsula Tech", site: "Powai Campus",
    type: "New Logo", industry: "IT / ITeS", city: "Mumbai", state: "Maharashtra",
    address: "Hiranandani, Powai, Mumbai 400076", lat: 19.1197, lng: 72.906,
    status: "pipeline_fy27", fy: "FY27", p: 35, close: "2027-01-31", owner: "Rohan Mehta",
    stage: "Needs Assessment", cr: 5.6, pax: 2600, biz: "B&I", map: "Mix", served: 0,
    services: "Multi-outlet, midnight meals, cafe", cpu: "cpu_mum",
    last: "Palatability tasting", lastOn: "2026-07-29", next: "Cafeteria utilisation study",
    nextOn: "2026-09-24", notes: "Incumbent in place until Mar 2027.",
  },
  {
    n: 19, acc: "coral", client: "Coral University", site: "Kalyan Campus",
    type: "New Logo", industry: "Higher Education", city: "Kalyan", state: "Maharashtra",
    address: "Kalyan-Shilphata Road, Kalyan 421204", lat: 19.235, lng: 73.1298,
    status: "universe", fy: "FY28", p: 10, close: "", owner: "Rohan Mehta",
    stage: "", cr: 2.2, pax: 3100, biz: "Education", map: "Map 1", served: 0,
    services: "Hostel mess, canteen", cpu: "cpu_mum",
    last: "Universe add from AISHE", lastOn: "2026-06-11", next: "Registrar outreach",
    nextOn: "2026-10-12", notes: "Distance from BKC CPU is the open question.",
  },
  {
    n: 20, acc: "marina_r", client: "Marina Retail HQ", site: "Lower Parel",
    type: "New Logo", industry: "Retail", city: "Mumbai", state: "Maharashtra",
    address: "Kamala Mills, Lower Parel, Mumbai 400013", lat: 19.0023, lng: 72.8298,
    status: "won", fy: "FY26", p: 100, close: "2026-02-14", owner: "Rohan Mehta",
    stage: "Closed Won", cr: 1.9, pax: 420, biz: "B&I", map: "Map 2", served: 420,
    services: "HQ cafe, pantry", cpu: "cpu_mum",
    last: "Live since April", lastOn: "2026-08-21", next: "Q2 NPS",
    nextOn: "2026-10-05", notes: "Won logo. Useful as a west-line reference.",
  },
  {
    n: 21, acc: "indus", client: "Indus Courier Hub", site: "Bhiwandi Sortation",
    type: "New Logo", industry: "Logistics", city: "Bhiwandi", state: "Maharashtra",
    address: "Bhiwandi Industrial, Thane 421302", lat: 19.2967, lng: 73.0631,
    status: "pipeline_fy28", fy: "FY28", p: 20, close: "2027-07-15", owner: "Kabir Khan",
    stage: "Discovery", cr: 2.7, pax: 1900, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "24x7 canteen, tea service", cpu: "cpu_mum",
    last: "Ops director call", lastOn: "2026-08-06", next: "Night-shift sample",
    nextOn: "2026-09-29", notes: "Odd hours. Hub growing with two more sheds FY28.",
  },
  {
    n: 22, acc: "pearl", client: "Pearl Pharma", site: "Thane R&D",
    type: "New Logo", industry: "Pharma", city: "Thane", state: "Maharashtra",
    address: "Wagle Estate, Thane 400604", lat: 19.1941, lng: 72.9588,
    status: "lost", fy: "FY26", p: 0, close: "2026-05-09", owner: "Rohan Mehta",
    stage: "Closed Lost", cr: 2.1, pax: 540, biz: "B&I", map: "Map 2", served: 0,
    services: "R&D cafe, restricted diets", cpu: "cpu_mum",
    last: "Lost — global GPO mandate", lastOn: "2026-05-09", next: "Watch 2027 GPO cycle",
    nextOn: "2027-02-01", notes: "Lost to global GPO. Geographically next to Peninsula and Sagar.",
  },
  {
    n: 23, acc: "summit", client: "Summit Motors", site: "Chakan Plant",
    type: "Retention", industry: "Automotive", city: "Pune", state: "Maharashtra",
    address: "Chakan MIDC Phase 2, Pune 410501", lat: 18.7604, lng: 73.8372,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Neha Kapoor",
    stage: "Live", cr: 10.2, pax: 6400, biz: "Manufacturing", map: "Map 1", served: 6400,
    services: "Industrial canteen, 3-shift, guest house", cpu: "cpu_pun",
    last: "Safety audit closeout", lastOn: "2026-08-18", next: "Wage revision impact",
    nextOn: "2026-09-21", notes: "Largest live manufacturing account. Reference for auto cluster.",
  },
  {
    n: 24, acc: "summit", client: "Summit Motors", site: "Hinjewadi Tech Centre",
    type: "Existing Expansion", industry: "Automotive", city: "Pune", state: "Maharashtra",
    address: "Hinjewadi Phase 1, Pune 411057", lat: 18.5971, lng: 73.7183,
    status: "pipeline_fy27", fy: "FY27", p: 60, close: "2026-11-30", owner: "Neha Kapoor",
    stage: "Commercials", cr: 2.9, pax: 1100, biz: "B&I", map: "Mix", served: 0,
    services: "Campus cafe, EV lab pantry", cpu: "cpu_pun",
    last: "Draft MSA aligned to Chakan", lastOn: "2026-09-01", next: "Plant HR alignment",
    nextOn: "2026-09-17", notes: "Expansion of Chakan relationship. CPU next door.",
  },
  {
    n: 25, acc: "orchid", client: "Orchid IT", site: "Hinjewadi Phase 3",
    type: "New Logo", industry: "IT / ITeS", city: "Pune", state: "Maharashtra",
    address: "Hinjewadi Phase 3, Pune 411057", lat: 18.5788, lng: 73.7375,
    status: "proposal_submitted", fy: "FY27", p: 55, close: "2026-10-08", owner: "Neha Kapoor",
    stage: "Submitted", cr: 4.7, pax: 2200, biz: "B&I", map: "Map 2", served: 0,
    services: "Food court, night meals", cpu: "cpu_pun",
    last: "Submitted to Jones Lang", lastOn: "2026-08-25", next: "Tech eval",
    nextOn: "2026-09-13", notes: "Clustered with Summit Hinjewadi — shared CPU economics.",
  },
  {
    n: 26, acc: "hillcrest", client: "Hillcrest College", site: "Kothrud",
    type: "New Logo", industry: "Higher Education", city: "Pune", state: "Maharashtra",
    address: "Karve Road, Kothrud, Pune 411038", lat: 18.5074, lng: 73.8077,
    status: "pipeline_fy26", fy: "FY26", p: 30, close: "2026-09-18", owner: "Neha Kapoor",
    stage: "Negotiation", cr: 1.8, pax: 1400, biz: "Education", map: "Map 1", served: 0,
    services: "Student mess, faculty dining", cpu: "cpu_pun",
    last: "Fee-hike objection", lastOn: "2026-05-27", next: "Revised commercial",
    nextOn: "2026-09-10", notes: "Stale FY26 deal. Student committee blocking price.",
  },
  {
    n: 27, acc: "granite", client: "Granite Healthcare", site: "Baner Hospital",
    type: "New Logo", industry: "Healthcare Provider", city: "Pune", state: "Maharashtra",
    address: "Baner-Pashan Link Road, Pune 411045", lat: 18.559, lng: 73.7866,
    status: "prospect_research", fy: "FY27", p: 20, close: "2027-03-01", owner: "Neha Kapoor",
    stage: "Discovery", cr: 3.3, pax: 760, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafe", cpu: "cpu_pun",
    last: "Website + bed-count research", lastOn: "2026-08-14", next: "CMO intro via Apex Care",
    nextOn: "2026-09-23", notes: "Can reference Apex Care Gurugram case.",
  },
  {
    n: 28, acc: "lotus", client: "Lotus Components", site: "Talegaon",
    type: "New Logo", industry: "Engineering", city: "Talegaon", state: "Maharashtra",
    address: "Talegaon MIDC, Pune 410507", lat: 18.7356, lng: 73.6754,
    status: "universe", fy: "FY28", p: 5, close: "", owner: "Neha Kapoor",
    stage: "", cr: 2.0, pax: 1250, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "Industrial canteen", cpu: "cpu_pun",
    last: "Added from MIDC list", lastOn: "2026-07-19", next: "Qualify pax",
    nextOn: "2026-10-20", notes: "Near Summit Chakan — cluster if we win density.",
  },
  {
    n: 29, acc: "cinder", client: "Cinder Tech", site: "Whitefield Campus",
    type: "Retention", industry: "IT / ITeS", city: "Bengaluru", state: "Karnataka",
    address: "ITPL Main Road, Whitefield, Bengaluru 560066", lat: 12.9851, lng: 77.7362,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Priya Nair",
    stage: "Live", cr: 12.4, pax: 5100, biz: "B&I", map: "Mix", served: 5100,
    services: "Campus F&B, CPU commissary, 5 outlets", cpu: "cpu_blr",
    last: "Outlet 5 renovation", lastOn: "2026-08-29", next: "Festival staffing",
    nextOn: "2026-10-02", notes: "Anchor Bengaluru account. Whitefield CPU built around this site.",
  },
  {
    n: 30, acc: "cinder", client: "Cinder Tech", site: "Electronic City",
    type: "Retention", industry: "IT / ITeS", city: "Bengaluru", state: "Karnataka",
    address: "Electronic City Phase 1, Bengaluru 560100", lat: 12.8452, lng: 77.6602,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Priya Nair",
    stage: "Live", cr: 6.1, pax: 2700, biz: "B&I", map: "Map 2", served: 2700,
    services: "Cafeteria, cafe, midnight meals", cpu: "cpu_blr",
    last: "Night-shift complaint close", lastOn: "2026-08-11", next: "EC Phase 2 bid",
    nextOn: "2026-09-26", notes: "CPU travel from Whitefield is tight at peak hours.",
  },
  {
    n: 31, acc: "redwood", client: "Redwood Hospitals", site: "Hebbal",
    type: "New Logo", industry: "Healthcare Provider", city: "Bengaluru", state: "Karnataka",
    address: "Hebbal, Bengaluru 560024", lat: 13.0358, lng: 77.597,
    status: "proposal_development", fy: "FY27", p: 50, close: "2026-12-05", owner: "Priya Nair",
    stage: "Solution Design", cr: 5.5, pax: 1250, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafeteria, visitor cafe", cpu: "cpu_blr",
    last: "Diet kitchen spec", lastOn: "2026-09-04", next: "NABH evidence pack",
    nextOn: "2026-09-18", notes: "Wants Siteline as second vendor after a failed incumbent.",
  },
  {
    n: 32, acc: "kanara", client: "Kanara Manufacturing", site: "Peenya Works",
    type: "New Logo", industry: "Engineering", city: "Bengaluru", state: "Karnataka",
    address: "Peenya Industrial Area, Bengaluru 560058", lat: 13.0286, lng: 77.5199,
    status: "pipeline_fy27", fy: "FY27", p: 40, close: "2027-02-12", owner: "Priya Nair",
    stage: "Needs Assessment", cr: 4.2, pax: 2900, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "Industrial canteen, 2-shift", cpu: "cpu_blr",
    last: "Union meeting observed", lastOn: "2026-07-08", next: "Re-open with new HR head",
    nextOn: "2026-09-30", notes: "Stale. Union prefers in-house cook staff.",
  },
  {
    n: 33, acc: "blueoak", client: "Blueoak University", site: "Yelahanka",
    type: "New Logo", industry: "Higher Education", city: "Bengaluru", state: "Karnataka",
    address: "Yelahanka, Bengaluru 560064", lat: 13.1155, lng: 77.606,
    status: "pipeline_fy26", fy: "FY26", p: 20, close: "2026-10-30", owner: "Priya Nair",
    stage: "Commercials", cr: 3.0, pax: 2200, biz: "Education", map: "Map 1", served: 0,
    services: "Hostel mess, kiosks", cpu: "cpu_blr",
    last: "Mess tender extended", lastOn: "2026-06-03", next: "Tender addendum",
    nextOn: "2026-09-27", notes: "FY26 leftover. Tender slipped twice.",
  },
  {
    n: 34, acc: "sparrow", client: "Sparrow Fintech", site: "Koramangala",
    type: "New Logo", industry: "BFSI", city: "Bengaluru", state: "Karnataka",
    address: "Koramangala 5th Block, Bengaluru 560095", lat: 12.9352, lng: 77.6245,
    status: "won", fy: "FY27", p: 100, close: "2026-07-22", owner: "Priya Nair",
    stage: "Closed Won", cr: 1.4, pax: 380, biz: "B&I", map: "Map 2", served: 380,
    services: "Cafe, pantry", cpu: "cpu_blr",
    last: "Go-live complete", lastOn: "2026-08-20", next: "30-day review",
    nextOn: "2026-09-19", notes: "Small won logo. Useful downtown reference.",
  },
  {
    n: 35, acc: "nimbus", client: "Nimbus BPO", site: "Whitefield SEZ",
    type: "New Logo", industry: "IT / ITeS", city: "Bengaluru", state: "Karnataka",
    address: "Graphite India Road, Whitefield, Bengaluru 560048", lat: 12.9734, lng: 77.7278,
    status: "lost", fy: "FY26", p: 0, close: "2026-06-18", owner: "Priya Nair",
    stage: "Closed Lost", cr: 3.8, pax: 1900, biz: "B&I", map: "Map 2", served: 0,
    services: "24x7 cafeteria", cpu: "cpu_blr",
    last: "Lost on transition risk", lastOn: "2026-06-18", next: "Rebid FY28",
    nextOn: "2027-04-01", notes: "Lost next door to Cinder Whitefield. Classic near-won miss.",
  },
  {
    n: 36, acc: "cedar", client: "Cedar Pharma", site: "Bommasandra",
    type: "New Logo", industry: "Pharma", city: "Bengaluru", state: "Karnataka",
    address: "Bommasandra Jigani Link, Bengaluru 560099", lat: 12.7995, lng: 77.6844,
    status: "prospect_research", fy: "FY27", p: 15, close: "2027-03-15", owner: "Priya Nair",
    stage: "Discovery", cr: 2.6, pax: 870, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "GMP canteen", cpu: "cpu_blr",
    last: "EHS policy review", lastOn: "2026-08-07", next: "Plant director mail",
    nextOn: "2026-09-21", notes: "South of Electronic City live site.",
  },
  {
    n: 37, acc: "deccanit", client: "Deccan IT", site: "HITEC City",
    type: "Retention", industry: "IT / ITeS", city: "Hyderabad", state: "Telangana",
    address: "Cyber Towers, HITEC City, Hyderabad 500081", lat: 17.4504, lng: 78.3808,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Arjun Reddy",
    stage: "Live", cr: 7.6, pax: 3400, biz: "B&I", map: "Mix", served: 3400,
    services: "Campus F&B, CPU, 3 outlets", cpu: "cpu_hyd",
    last: "Ramzan menu closeout", lastOn: "2026-08-05", next: "Bathukamma specials",
    nextOn: "2026-09-28", notes: "CPU sits inside this campus. Density engine for Hyderabad.",
  },
  {
    n: 38, acc: "charminar", client: "Charminar Hospitals", site: "Banjara Hills",
    type: "New Logo", industry: "Healthcare Provider", city: "Hyderabad", state: "Telangana",
    address: "Road No. 12, Banjara Hills, Hyderabad 500034", lat: 17.4126, lng: 78.444,
    status: "pipeline_fy27", fy: "FY27", p: 40, close: "2026-12-22", owner: "Arjun Reddy",
    stage: "Needs Assessment", cr: 4.0, pax: 820, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafeteria", cpu: "cpu_hyd",
    last: "Kitchen audit", lastOn: "2026-08-27", next: "CMO tasting",
    nextOn: "2026-09-16", notes: "Premium hospital. Brand-sensitive menus.",
  },
  {
    n: 39, acc: "saffron", client: "Saffron Manufacturing", site: "Genome Valley",
    type: "New Logo", industry: "Pharma", city: "Hyderabad", state: "Telangana",
    address: "Genome Valley, Shameerpet, Hyderabad 500078", lat: 17.5918, lng: 78.5802,
    status: "proposal_submitted", fy: "FY27", p: 60, close: "2026-10-20", owner: "Arjun Reddy",
    stage: "Submitted", cr: 5.9, pax: 2400, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "GMP canteen, 2-shift", cpu: "cpu_hyd",
    last: "Proposal submitted", lastOn: "2026-08-31", next: "Technical clarification",
    nextOn: "2026-09-15", notes: "Far from HITEC CPU — on-site kitchen is the model.",
  },
  {
    n: 40, acc: "nilgiri", client: "Nilgiri College", site: "Gachibowli",
    type: "New Logo", industry: "Higher Education", city: "Hyderabad", state: "Telangana",
    address: "Gachibowli, Hyderabad 500032", lat: 17.4401, lng: 78.3489,
    status: "universe", fy: "FY28", p: 10, close: "", owner: "Arjun Reddy",
    stage: "", cr: 1.7, pax: 1600, biz: "Education", map: "Map 1", served: 0,
    services: "Student mess", cpu: "cpu_hyd",
    last: "Universe add", lastOn: "2026-07-22", next: "Dean intro",
    nextOn: "2026-10-14", notes: "Walkable to Deccan IT campus — cluster with existing.",
  },
  {
    n: 41, acc: "quartz", client: "Quartz Bank", site: "Financial District",
    type: "New Logo", industry: "BFSI", city: "Hyderabad", state: "Telangana",
    address: "Nanakramguda, Hyderabad 500032", lat: 17.4213, lng: 78.3446,
    status: "pipeline_fy26", fy: "FY26", p: 35, close: "2026-09-25", owner: "Arjun Reddy",
    stage: "Negotiation", cr: 3.5, pax: 960, biz: "B&I", map: "Map 2", served: 0,
    services: "HQ cafe, pantry", cpu: "cpu_hyd",
    last: "Legal redlines", lastOn: "2026-09-02", next: "MSA close",
    nextOn: "2026-09-11", notes: "Closing this month. CPU-served from HITEC.",
  },
  {
    n: 42, acc: "coromandel", client: "Coromandel Tech", site: "OMR Campus",
    type: "Retention", industry: "IT / ITeS", city: "Chennai", state: "Tamil Nadu",
    address: "OMR, Thoraipakkam, Chennai 600097", lat: 12.9492, lng: 80.2411,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Meera Iyer",
    stage: "Live", cr: 6.8, pax: 2900, biz: "B&I", map: "Mix", served: 2900,
    services: "Campus F&B, CPU", cpu: "cpu_che",
    last: "Pongal planning", lastOn: "2026-08-24", next: "Navaratri menu",
    nextOn: "2026-09-29", notes: "Anchor Chennai account. OMR CPU on campus edge.",
  },
  {
    n: 43, acc: "marina_h", client: "Marina Hospitals", site: "T. Nagar",
    type: "New Logo", industry: "Healthcare Provider", city: "Chennai", state: "Tamil Nadu",
    address: "T. Nagar, Chennai 600017", lat: 13.0418, lng: 80.2337,
    status: "pipeline_fy28", fy: "FY28", p: 25, close: "2027-05-30", owner: "Meera Iyer",
    stage: "Discovery", cr: 3.7, pax: 700, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafe", cpu: "cpu_che",
    last: "Intro via Coromandel CHRO", lastOn: "2026-08-13", next: "Kitchen tour",
    nextOn: "2026-09-22", notes: "Early FY28 seed. City-centre vs OMR CPU time.",
  },
  {
    n: 44, acc: "pallava", client: "Pallava Auto", site: "Sriperumbudur",
    type: "New Logo", industry: "Automotive", city: "Sriperumbudur", state: "Tamil Nadu",
    address: "SIPCOT, Sriperumbudur 602105", lat: 12.9676, lng: 79.9489,
    status: "proposal_development", fy: "FY27", p: 45, close: "2026-11-28", owner: "Meera Iyer",
    stage: "Solution Design", cr: 8.1, pax: 4700, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "Industrial canteen, 3-shift", cpu: "cpu_che",
    last: "Layout + manpower model", lastOn: "2026-09-03", next: "Japanese principal call",
    nextOn: "2026-09-17", notes: "High pax auto. On-site kitchen; CPU too far for bulk hot meals.",
  },
  {
    n: 45, acc: "bayleaf", client: "Bayleaf University", site: "Tambaram",
    type: "New Logo", industry: "Higher Education", city: "Chennai", state: "Tamil Nadu",
    address: "Tambaram, Chennai 600045", lat: 12.9249, lng: 80.1,
    status: "prospect_research", fy: "FY27", p: 15, close: "2027-01-10", owner: "Meera Iyer",
    stage: "Discovery", cr: 2.3, pax: 2100, biz: "Education", map: "Map 1", served: 0,
    services: "Hostel mess", cpu: "cpu_che",
    last: "Prospect research note", lastOn: "2026-07-30", next: "Registrar letter",
    nextOn: "2026-09-25", notes: "Mess currently in-house. Quality complaints on social.",
  },
  {
    n: 46, acc: "sabarmati", client: "Sabarmati Textiles", site: "Narol Mill",
    type: "New Logo", industry: "FMCG", city: "Ahmedabad", state: "Gujarat",
    address: "Narol, Ahmedabad 382405", lat: 22.9732, lng: 72.5901,
    status: "pipeline_fy27", fy: "FY27", p: 35, close: "2026-12-15", owner: "Kabir Khan",
    stage: "Needs Assessment", cr: 3.2, pax: 2500, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "Industrial canteen", cpu: "cpu_amd",
    last: "Mill visit", lastOn: "2026-08-10", next: "Labour contractor map",
    nextOn: "2026-09-18", notes: "First Gujarat manufacturing pursuit at scale.",
  },
  {
    n: 47, acc: "amber", client: "Amber IT", site: "Jaipur SEZ",
    type: "New Logo", industry: "IT / ITeS", city: "Jaipur", state: "Rajasthan",
    address: "Mahindra SEZ, Jaipur 302037", lat: 26.885, lng: 75.7384,
    status: "universe", fy: "FY28", p: 5, close: "", owner: "Vikram Singh",
    stage: "", cr: 2.5, pax: 1300, biz: "B&I", map: "Map 1", served: 0,
    services: "Campus cafeteria", cpu: "",
    last: "Universe add", lastOn: "2026-06-28", next: "Assign kitchen strategy",
    nextOn: "2026-10-30", notes: "No CPU assigned. Greenfield kitchen if we pursue.",
  },
  {
    n: 48, acc: "malabar", client: "Malabar Hospitals", site: "Kochi Centre",
    type: "New Logo", industry: "Healthcare Provider", city: "Kochi", state: "Kerala",
    address: "Ernakulam, Kochi 682016", lat: 9.9816, lng: 76.2999,
    status: "prospect_research", fy: "FY28", p: 15, close: "2027-04-12", owner: "Meera Iyer",
    stage: "Discovery", cr: 2.9, pax: 640, biz: "Healthcare", map: "Mix", served: 0,
    services: "Patient meals, staff cafe", cpu: "",
    last: "Kerala market scan", lastOn: "2026-08-02", next: "Partner kitchen options",
    nextOn: "2026-10-06", notes: "No Siteline CPU in Kerala yet. Feasibility is the story.",
  },
  {
    n: 49, acc: "hooghly", client: "Hooghly Engineering", site: "Salt Lake Works",
    type: "Retention", industry: "Engineering", city: "Kolkata", state: "West Bengal",
    address: "Salt Lake Sector V, Kolkata 700091", lat: 22.5734, lng: 88.4342,
    status: "existing_client", fy: "", p: 100, close: "", owner: "Kabir Khan",
    stage: "Live", cr: 4.5, pax: 1800, biz: "Manufacturing", map: "Mix", served: 1800,
    services: "Industrial canteen, cafe", cpu: "cpu_kol",
    last: "Durga Puja roster", lastOn: "2026-08-17", next: "Puja shutdown plan",
    nextOn: "2026-09-20", notes: "Only live East account. CPU on the same block.",
  },
  {
    n: 50, acc: "gomti", client: "Gomti University", site: "Lucknow Campus",
    type: "New Logo", industry: "Higher Education", city: "Lucknow", state: "Uttar Pradesh",
    address: "Gomti Nagar, Lucknow 226010", lat: 26.8512, lng: 81.0078,
    status: "pipeline_fy26", fy: "FY26", p: 25, close: "2026-10-12", owner: "Vikram Singh",
    stage: "Commercials", cr: 2.1, pax: 2800, biz: "Education", map: "Map 1", served: 0,
    services: "Hostel mess", cpu: "",
    last: "Tender queries", lastOn: "2026-05-09", next: "Re-bid decision",
    nextOn: "2026-09-14", notes: "No CPU. Stale. High pax education in a white space city.",
  },
  {
    n: 51, acc: "malwa", client: "Malwa Auto", site: "Pithampur",
    type: "New Logo", industry: "Automotive", city: "Indore", state: "Madhya Pradesh",
    address: "Pithampur Industrial, Dhar 454775", lat: 22.6101, lng: 75.6822,
    status: "pipeline_fy27", fy: "FY27", p: 30, close: "2027-01-28", owner: "Kabir Khan",
    stage: "Needs Assessment", cr: 5.4, pax: 3100, biz: "Manufacturing", map: "Map 1", served: 0,
    services: "Industrial canteen, 3-shift", cpu: "",
    last: "Plant tour", lastOn: "2026-08-09", next: "Greenfield kitchen model",
    nextOn: "2026-09-28", notes: "No CPU. High pax. Would need on-site kitchen from day one.",
  },
  {
    n: 52, acc: "shivalik", client: "Shivalik Bank", site: "Chandigarh HQ",
    type: "New Logo", industry: "BFSI", city: "Chandigarh", state: "Chandigarh",
    address: "Sector 9, Chandigarh 160009", lat: 30.7472, lng: 76.7933,
    status: "proposal_development", fy: "FY27", p: 40, close: "2026-11-08", owner: "Vikram Singh",
    stage: "Solution Design", cr: 1.6, pax: 340, biz: "B&I", map: "Map 2", served: 0,
    services: "HQ cafe, pantry", cpu: "",
    last: "Concept deck", lastOn: "2026-08-23", next: "Facilities walkthrough",
    nextOn: "2026-09-19", notes: "Small HQ. North cluster with NCR owners. No CPU yet.",
  },
];

function pad(n: number): string {
  return String(n).padStart(3, "0");
}

export function buildSampleAccounts(kitchens: CentralKitchen[] = KITCHENS): AccountRecord[] {
  const now = "2026-09-06T08:00:00.000Z";
  return SEED.map((s) => {
    const rec: AccountRecord = {
      id: `sit_${pad(s.n)}`,
      accountId: `acc_${s.acc}`,
      clientName: s.client,
      accountType: s.type,
      industry: s.industry,
      siteId: `ste_${pad(s.n)}`,
      siteName: s.site,
      city: s.city,
      state: s.state,
      address: s.address,
      lat: s.lat,
      lng: s.lng,
      opportunityId: `opp_${pad(s.n)}`,
      status: s.status,
      pipelineFy: s.fy,
      probability: s.p,
      expectedClosureDate: s.close,
      owner: s.owner,
      proposalStage: s.stage,
      estimatedRevenue: Math.round(s.cr * 1e7),
      estimatedPax: s.pax,
      businessType: s.biz,
      mapType: s.map,
      paxBeingServed: s.served,
      servicesRequired: s.services,
      kitchenId: s.cpu,
      distanceKm: null,
      roadDistanceKm: null,
      travelMinutes: null,
      lastActivity: s.last,
      lastActivityDate: s.lastOn,
      nextAction: s.next,
      nextActionDate: s.nextOn,
      notes: s.notes,
      createdAt: now,
      updatedAt: now,
    };
    return applyKitchen(rec, kitchens);
  });
}

export const SAMPLE_ACCOUNTS = buildSampleAccounts();
